In [24]:
# testing new parquet with transit

In [2]:
#! pip install cpi

In [1]:
import pandas as pd
from siuba import *

In [2]:
df = pd.read_parquet('dla_df.parquet')

In [23]:
#old run
df>>filter(_.transit==1)>>count(_.type_of_work)>>arrange(-_.n)

                                          type_of_work  n
357   Public Outreach And Marketing For "the Bus" (tc)  9
52                        Class 1 Multi-use Trail (tc)  8
122                            Construct Class I Trail  8
172  Emergency Force Account Agreement With Apex Fe...  8
277  Install Temporary Traffic Signs, Remove And Re...  8
..                                                 ... ..
502  Upgrade The Existing Non-conforming And/or Dam...  1
504                     Walking School Bus Safety Prog  1
506  Widen And Construct Bus/carpool Lanes, Transit...  1
507        Widen And Pave Shoulders, Install Guardrail  1
514                         _const. Class I Bike Trail  1

[515 rows x 2 columns]

In [28]:
#new run. expecting no trail
df>>filter(_.transit==1)>>count(_.type_of_work)>>arrange(-_.n)

                                          type_of_work  n
137   Public Outreach And Marketing For "the Bus" (tc)  9
12                             Bridge Rail Replacement  7
13                        Bridge Rail Replacement (tc)  7
208  Upgrade Traffic System Controller; Brt Phase( Tc)  6
212           Yarts Public Outreach And Marketing (tc)  6
..                                                 ... ..
201  Translink Fare Collection System Fy 2010/2011 ...  1
202       Union Station Master Plan:alameda Esplanade.  1
205  Upgrade A Total Of 3,073 Feet Of 'tuthill' Rai...  1
209                     Walking School Bus Safety Prog  1
210  Widen And Construct Bus/carpool Lanes, Transit...  1

[216 rows x 2 columns]

In [29]:
#works as expected

In [4]:
pd.set_option("display.max_columns", 100)
pd.set_option('display.max_colwidth', 1000)

In [7]:
#Checking to see if the processing days worked
df.sample()

,location,prefix,project_no,agency,prepared_date,submit__to_hq_date,hq_review_date,submit_to_fhwa_date,to_fmis_date,fed_requested,ac_requested,total_requested,status_comment,locode,dist,status,dist_processing_days,hq_processing_days,fhwa_processing_days,ftip_no,project_location,type_of_work,seq,date_request_initiated,date_completed_request,mpo,projectID,prepared_y,process_days,primary_agency_name,adjusted_total_requested,adjusted_fed_requested,adjusted_ac_requested,active_transp,transit,bridge,street,freeway,infra_resiliency_er,congestion_relief,work_categories
6838,Obligated,BRLO,5914(080),Lake County,2016-04-25,2016-04-26,2016-05-04,2016-05-08,2016-05-12,1218000.0,0.0,1218000.0,Authorized,5914,1,E-76 approved on Prepared on 10/6/2015,1.0,12.0,4.0,HBPLOCAL,Two Miles West Of Sr-29 On Dry Creek Road; Cr-114,Replace Single Lane Bridge (tc),3,NaT,NaT,NON-MPO,5914,2016.0,17.0,Lake County,1.375132e+06,1.375132e+06,0.0,0,0,1,0,0,1,0,2

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21059 entries, 0 to 21664
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   location                  21059 non-null  object
 1   prefix                    21059 non-null  object
 2   project_no                21059 non-null  object
 3   agency                    21059 non-null  object
 4   prepared_date             21044 non-null  datetime64[ns]
 5   submit__to_hq_date        20948 non-null  datetime64[ns]
 6   hq_review_date            20922 non-null  datetime64[ns]
 7   submit_to_fhwa_date       20872 non-null  datetime64[ns]
 8   to_fmis_date              20871 non-null  datetime64[ns]
 9   fed_requested             21058 non-null  float64
 10  ac_requested              21059 non-null  float64
 11  total_requested           21058 non-null  float64
 12  status_comment            21059 non-null  object
 13  locode                    21059 non-null  object
 14  dist                      21059 non-null  int64
 15  status                    21059 non-null  object
 16  dist_processing_days      19296 non-null  float64
 17  hq_processing_days        20878 non-null  float64
 18  fhwa_processing_days      20878 non-null  float64
 19  ftip_no                   21059 non-null  object
 20  project_location          20591 non-null  object
 21  type_of_work              21059 non-null  object
 22  seq                       21059 non-null  int64
 23  date_request_initiated    10593 non-null  datetime64[ns]
 24  date_completed_request    10422 non-null  datetime64[ns]
 25  mpo                       21058 non-null  object
 26  projectID                 21059 non-null  object
 27  prepared_y                21044 non-null  float64
 28  process_days              19220 non-null  float64
 29  primary_agency_name       21055 non-null  object
 30  adjusted_total_requested  21043 non-null  float64
 31  adjusted_fed_requested    21043 non-null  float64
 32  adjusted_ac_requested     21044 non-null  float64
 33  active_transp             21059 non-null  int64
 34  transit                   21059 non-null  int64
 35  bridge                    21059 non-null  int64
 36  street                    21059 non-null  int64
 37  freeway                   21059 non-null  int64
 38  infra_resiliency_er       21059 non-null  int64
 39  congestion_relief         21059 non-null  int64
 40  work_categories           21059 non-null  int64
dtypes: datetime64[ns](7), float64(11), int64(10), object(13)
memory usage: 6.7+ MB