In [1]:
# import os
# os.environ["CALITP_BQ_MAX_BYTES"] = str(100_000_000_000)

import pandas as pd
import numpy as np
import geopandas as gpd
# import fiona
import datetime as dt

# from utils import *

import calitp
from calitp.tables import tbl
from siuba import *

/Users/edasmalchi/anaconda3/envs/pd1/lib/python3.9/site-packages/google/auth/_default.py:68: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [2]:
static_stops = tbl.gtfs_schedule.stops()

In [3]:
static_stops

,calitp_itp_id,calitp_url_number,stop_id,tts_stop_name,stop_lat,stop_lon,zone_id,parent_station,stop_code,stop_name,stop_desc,stop_url,location_type,stop_timezone,wheelchair_boarding,level_id,platform_code,calitp_extracted_at
0,2,6,890002,None,37.794360,-122.390790,None,2455444,890002,San Francisco Ferry Building (Gate G),None,None,0,None,0,None,None,2021-04-16
1,2,6,12048536,None,37.736528,-122.256966,None,None,12048536,Harbor Bay Ferry Terminal,None,None,0,America/Los_Angeles,1,None,None,2021-04-16
2,2,6,12048537,None,37.796869,-122.393209,None,2455444,12048537,San Francisco Ferry Building (Gate B),None,None,0,None,1,None,None,2021-04-16
3,2,6,12030041,None,37.662676,-122.377245,None,None,12030041,South San Francisco,None,None,0,America/Los_Angeles,1,None,None,2021-04-16
4,2,6,12149044,None,38.099884,-122.263077,None,None,12149044,Vallejo Ferry Terminal,None,None,0,America/Los_Angeles,1,None,None,2021-04-16