# LAX Metro Center opening

LA Metro: https://www.metro.net/lax-metro-transit-center/
* Rail routes: C and K Lines
* Bus routes: 102, 111, 117, 120, 232
* Big Blue: 3
* Culver: 6, Rapid 6
* Torrance: T8
* GTrans: 5
* Beach Cities: 109

https://transit.torranceca.gov/routes-schedules/line-8

In [1]:
import pandas as pd
import utils

In [2]:
dim_trips = pd.read_parquet(
    "dim_trips.parquet",
    filters = [[
        ("feed_key", "in", list(utils.feed_to_name_dict.keys())),
    ]],
    columns = ["feed_key", "route_id", "service_id", "trip_id"]
).pipe(utils.get_operator_lax_routes)

dim_calendar = pd.read_parquet(
    "dim_calendar.parquet",
    filters = [[("feed_key", "in", utils.subset_feeds)]],
    columns = ["feed_key", "service_id", "start_date", "end_date"]
)

df = pd.merge(
    dim_calendar,
    dim_trips,
    on = ["feed_key", "service_id"],
    how = "inner"
)

In [3]:
results = (
    df.groupby(["gtfs_dataset_name", "route_name"])
    .agg({
        "start_date": lambda x: list(set(x)),
        "end_date": lambda x: list(set(x))
    }).reset_index()
)

results

,gtfs_dataset_name,route_name,start_date,end_date
0,Beach Cities GMV Schedule,Beach Cities Transit 109 (GMV),[2023-08-07],[2099-12-31]
1,Beach Cities Schedule,Beach Cities Transit 109 NB,[2020-01-01],[2023-01-01]
2,Beach Cities Schedule,Beach Cities Transit 109 SB,[2020-01-01],[2023-01-01]
3,Big Blue Bus Schedule,BBB 3 Lincoln Boulevard/LAX,[2025-04-06],[2025-08-09]
4,Big Blue Bus Schedule,BBB R3 Lincoln Boulevard/LAX,[2025-04-06],[2025-08-09]
5,Big Blue Bus Swiftly Schedule,BBB 3 Lincoln Blvd/LAX (Swiftly),[2025-04-06],[2025-08-09]
6,Big Blue Bus Swiftly Schedule,BBB 3 Lincoln Blvd/LAX Rapid (Swiftly),[2025-04-06],[2025-08-09]
7,Culver City Schedule,Culver 6 Sepulveda,[2025-05-05],[2025-06-15]
8,G Trans Schedule,G Trans 5,[2025-05-04],[2025-07-19]
9,LA Metro Bus Schedule,Metro 102,"[2025-01-19, 2025-01-25, 2025-01-20]","[2025-06-21, 2025-06-20, 2025-06-15]"
10,LA Metro Bus Schedule,Metro 111,"[2025-01-19, 2025-01-25, 2025-01-20]","[2025-06-21, 2025-06-20, 2025-06-15]"
11,LA Metro Bus Schedule,Metro 117,"[2025-01-19, 2025-01-25, 2025-01-20]","[2025-06-21, 2025-06-20, 2025-06-15]"
12,LA Metro Bus Schedule,Metro 120,"[2025-01-19, 2025-01-25, 2025-01-20]","[2025-06-21, 2025-06-20, 2025-06-15]"
13,LA Metro Bus Schedule,Metro 232,"[2025-01-19, 2025-01-25, 2025-01-20]","[2025-06-21, 2025-06-20, 2025-06-15]"
14,LA Metro Rail Schedule,Metro C Line,"[2025-05-27, 2025-06-01, 2025-06-07, 2025-05-3...","[2025-06-10, 2025-06-01, 2025-05-29, 2025-06-0..."
15,LA Metro Rail Schedule,Metro K Line,"[2025-05-27, 2025-06-01, 2025-06-07, 2025-05-3...","[2025-06-10, 2025-06-01, 2025-05-29, 2025-06-0..."
16,LAX FlyAway Schedule,LAX FlyAway Schedule LAX to Union Station,[2023-07-05],[2025-05-24]
17,LAX FlyAway Schedule,LAX FlyAway Schedule LAX to Van Nuys,[2023-07-05],[2025-05-24]
18,LAX Flyaway Bus Schedule,LAX Flyaway Bus Schedule LAX to Union Station,[2023-07-05],[2027-12-30]
19,LAX Shuttles Schedule,LAX Flyaway Bus Schedule LAX to Union Station,[2024-11-03],[2050-12-30]
20,Torrance Schedule,Torrance 8,[2025-04-06],[2025-07-12]