In [1]:
from calitp_data_analysis.tables import tbls

In [2]:
import calitp_data_analysis.magics

In [3]:
import pandas as pd

In [4]:
%%sql

SELECT
    COUNT(*)
FROM `mart_gtfs.dim_schedule_feeds`
WHERE
    key = "db58891de4281f965b4e7745675415ab"
LIMIT 10

   f0_
0    1

In [5]:
tbls.mart_gtfs.dim_agency()

,key,_gtfs_key,feed_key,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_fare_url,agency_email,base64_url,_dt,_feed_valid_from,_line_number,feed_timezone
0,a196a8996bb74b7bd6d92f0cc2802620,00e77c29f2ce1986407cb93f53936dff,25915c089571c49be33b59e10c25d2ac,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-15,2022-09-15 00:01:13+00:00,1,America/Los_Angeles
1,1d48492cd90930d6612fc70ef18bf8d4,93c44e614219c41696a8148018c1d83b,f87ac9abe81a7548325423ede69c3b86,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-09,2022-09-09 00:00:56+00:00,1,America/Los_Angeles
2,033d018b031002914fbfa48c872d4a65,8f5e204872e6b7034479a6d11502547b,3d30b02b9008f788eb89c41c137786c1,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2022-01-19,2022-01-19 00:11:01+00:00,1,America/Los_Angeles
3,282b4e07171c48ac08162e0dc8749066,18fcf47148228c7b56c19726c854054b,9b8e9b8befe560293a6c5b38dc19ffbb,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2021-07-28,2021-07-28 13:56:16+00:00,1,America/Los_Angeles
4,fdbd4bd9cc406a651ec80dba6ac4a1c1,ebfb64604b1c18bdf8ab91a2e4394491,ba587fd71b4f9a956ff36e309e6acf3f,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-05-14,2022-05-14 00:01:18+00:00,1,America/Los_Angeles

In [6]:
df1 = tbls.mart_gtfs.dim_agency()

In [7]:
type(df1)

siuba.sql.backend.LazyTbl

In [8]:
df1['feed_key']

TypeError: 'LazyTbl' object is not subscriptable

In [9]:
df2 = pd.DataFrame(df1)

ValueError: DataFrame constructor not properly called!

In [25]:
tbls.mart_gtfs.dim_agency() >> collect()

NameError: name 'collect' is not defined

In [4]:
from siuba import collect

In [29]:
df2 = tbls.mart_gtfs.dim_agency() >> collect()

In [33]:
df2['key']

0        56112d81d62d71d408ea0247309178e4
1        033d018b031002914fbfa48c872d4a65
2        1d48492cd90930d6612fc70ef18bf8d4
3        a196a8996bb74b7bd6d92f0cc2802620
4        282b4e07171c48ac08162e0dc8749066
                       ...
64250    4b3a0475f412b43b2193162af67b6d5e
64251    8036aa61601f9639e38e5badc9e695e5
64252    d68573068cee2b62d39d4ec2984cfe4b
64253    d6be150d01ed7bf9ad331b36bac61b30
64254    280057e38f45d53dbf28a93696cf4bee
Name: key, Length: 64255, dtype: object

In [34]:
df2.head()

,key,_gtfs_key,feed_key,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_fare_url,agency_email,base64_url,_dt,_feed_valid_from,_line_number,feed_timezone
0,56112d81d62d71d408ea0247309178e4,090343c89ab8fe1d5e3b79e5687bbcca,21fa0b125d801eb5058da2ec5d748bda,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-15,2022-09-15 14:59:54.274779+00:00,1,America/Los_Angeles
1,033d018b031002914fbfa48c872d4a65,8f5e204872e6b7034479a6d11502547b,3d30b02b9008f788eb89c41c137786c1,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2022-01-19,2022-01-19 00:11:01+00:00,1,America/Los_Angeles
2,1d48492cd90930d6612fc70ef18bf8d4,93c44e614219c41696a8148018c1d83b,f87ac9abe81a7548325423ede69c3b86,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-09,2022-09-09 00:00:56+00:00,1,America/Los_Angeles
3,a196a8996bb74b7bd6d92f0cc2802620,00e77c29f2ce1986407cb93f53936dff,25915c089571c49be33b59e10c25d2ac,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-15,2022-09-15 00:01:13+00:00,1,America/Los_Angeles
4,282b4e07171c48ac08162e0dc8749066,18fcf47148228c7b56c19726c854054b,9b8e9b8befe560293a6c5b38dc19ffbb,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2021-07-28,2021-07-28 13:56:16+00:00,1,America/Los_Angeles

In [35]:
df2.dtypes

key                              object
_gtfs_key                        object
feed_key                         object
agency_id                        object
agency_name                      object
agency_url                       object
agency_timezone                  object
agency_lang                      object
agency_phone                     object
agency_fare_url                  object
agency_email                     object
base64_url                       object
_dt                              object
_feed_valid_from    datetime64[ns, UTC]
_line_number                      int64
feed_timezone                    object
dtype: object

In [39]:
type(df2)

pandas.core.frame.DataFrame

In [44]:
type(df2['key'])

pandas.core.series.Series

In [51]:
%%sql

select * from `mart_gtfs.dim_agency`

,key,_gtfs_key,feed_key,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_fare_url,agency_email,base64_url,_dt,_feed_valid_from,_line_number,feed_timezone
0,56112d81d62d71d408ea0247309178e4,090343c89ab8fe1d5e3b79e5687bbcca,21fa0b125d801eb5058da2ec5d748bda,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-15,2022-09-15 14:59:54.274779+00:00,1,America/Los_Angeles
1,033d018b031002914fbfa48c872d4a65,8f5e204872e6b7034479a6d11502547b,3d30b02b9008f788eb89c41c137786c1,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2022-01-19,2022-01-19 00:11:01+00:00,1,America/Los_Angeles
2,1d48492cd90930d6612fc70ef18bf8d4,93c44e614219c41696a8148018c1d83b,f87ac9abe81a7548325423ede69c3b86,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-09,2022-09-09 00:00:56+00:00,1,America/Los_Angeles
3,a196a8996bb74b7bd6d92f0cc2802620,00e77c29f2ce1986407cb93f53936dff,25915c089571c49be33b59e10c25d2ac,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-15,2022-09-15 00:01:13+00:00,1,America/Los_Angeles
4,282b4e07171c48ac08162e0dc8749066,18fcf47148228c7b56c19726c854054b,9b8e9b8befe560293a6c5b38dc19ffbb,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2021-07-28,2021-07-28 13:56:16+00:00,1,America/Los_Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64250,4b3a0475f412b43b2193162af67b6d5e,53614dfeecf131052270c150f758385d,77b6f917c93cd0df914c4464babd89fb,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-21,2023-06-21 03:00:44.374286+00:00,51,America/New_York
64251,8036aa61601f9639e38e5badc9e695e5,0460c4af1cff0625899b79263efb4de9,7582dbee0bae7096dc852dbb1b08bfae,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-12,2023-06-12 03:00:19.345342+00:00,51,America/New_York
64252,d68573068cee2b62d39d4ec2984cfe4b,d4658c02796555dd0d7c2eb7e4591a72,c1e6cc82b6d90b887502c1968249bd09,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-14,2023-06-14 03:00:25.051132+00:00,51,America/New_York
64253,d6be150d01ed7bf9ad331b36bac61b30,4778fc73f3171660f3e238fee43d2cd3,78b7c565f05f6a62fd2b89b570ead696,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-17,2023-06-17 03:00:20.081767+00:00,51,America/New_York
64254,280057e38f45d53dbf28a93696cf4bee,baa4244fdd157a9af14e7d38469252eb,fe8f5d682c171239888eb51be6d14208,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-13,2023-06-13 03:00:31.783490+00:00,51,America/New_York

In [49]:
tbls.mart_gtfs.dim_agency() >> collect()

,key,_gtfs_key,feed_key,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_fare_url,agency_email,base64_url,_dt,_feed_valid_from,_line_number,feed_timezone
0,56112d81d62d71d408ea0247309178e4,090343c89ab8fe1d5e3b79e5687bbcca,21fa0b125d801eb5058da2ec5d748bda,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-15,2022-09-15 14:59:54.274779+00:00,1,America/Los_Angeles
1,033d018b031002914fbfa48c872d4a65,8f5e204872e6b7034479a6d11502547b,3d30b02b9008f788eb89c41c137786c1,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2022-01-19,2022-01-19 00:11:01+00:00,1,America/Los_Angeles
2,1d48492cd90930d6612fc70ef18bf8d4,93c44e614219c41696a8148018c1d83b,f87ac9abe81a7548325423ede69c3b86,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-09,2022-09-09 00:00:56+00:00,1,America/Los_Angeles
3,a196a8996bb74b7bd6d92f0cc2802620,00e77c29f2ce1986407cb93f53936dff,25915c089571c49be33b59e10c25d2ac,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-15,2022-09-15 00:01:13+00:00,1,America/Los_Angeles
4,282b4e07171c48ac08162e0dc8749066,18fcf47148228c7b56c19726c854054b,9b8e9b8befe560293a6c5b38dc19ffbb,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2021-07-28,2021-07-28 13:56:16+00:00,1,America/Los_Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64250,4b3a0475f412b43b2193162af67b6d5e,53614dfeecf131052270c150f758385d,77b6f917c93cd0df914c4464babd89fb,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-21,2023-06-21 03:00:44.374286+00:00,51,America/New_York
64251,8036aa61601f9639e38e5badc9e695e5,0460c4af1cff0625899b79263efb4de9,7582dbee0bae7096dc852dbb1b08bfae,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-12,2023-06-12 03:00:19.345342+00:00,51,America/New_York
64252,d68573068cee2b62d39d4ec2984cfe4b,d4658c02796555dd0d7c2eb7e4591a72,c1e6cc82b6d90b887502c1968249bd09,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-14,2023-06-14 03:00:25.051132+00:00,51,America/New_York
64253,d6be150d01ed7bf9ad331b36bac61b30,4778fc73f3171660f3e238fee43d2cd3,78b7c565f05f6a62fd2b89b570ead696,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-17,2023-06-17 03:00:20.081767+00:00,51,America/New_York
64254,280057e38f45d53dbf28a93696cf4bee,baa4244fdd157a9af14e7d38469252eb,fe8f5d682c171239888eb51be6d14208,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-13,2023-06-13 03:00:31.783490+00:00,51,America/New_York

In [1]:
from calitp_data_analysis.sql import query_sql

In [53]:
df_dim_agency = query_sql("""

select * 
from `mart_gtfs.dim_agency`

""", as_df = True)

In [54]:
df_dim_agency

,key,_gtfs_key,feed_key,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_fare_url,agency_email,base64_url,_dt,_feed_valid_from,_line_number,feed_timezone
0,56112d81d62d71d408ea0247309178e4,090343c89ab8fe1d5e3b79e5687bbcca,21fa0b125d801eb5058da2ec5d748bda,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-15,2022-09-15 14:59:54.274779+00:00,1,America/Los_Angeles
1,033d018b031002914fbfa48c872d4a65,8f5e204872e6b7034479a6d11502547b,3d30b02b9008f788eb89c41c137786c1,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2022-01-19,2022-01-19 00:11:01+00:00,1,America/Los_Angeles
2,1d48492cd90930d6612fc70ef18bf8d4,93c44e614219c41696a8148018c1d83b,f87ac9abe81a7548325423ede69c3b86,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-09,2022-09-09 00:00:56+00:00,1,America/Los_Angeles
3,a196a8996bb74b7bd6d92f0cc2802620,00e77c29f2ce1986407cb93f53936dff,25915c089571c49be33b59e10c25d2ac,LAX FlyAway,None,http://www.LAXFlyAway.org,America/Los_Angeles,en,(714) 507-1170,None,None,aHR0cHM6Ly93d3cuZmx5bGF4LmNvbS8tL21lZGlhL2ZseW...,2022-09-15,2022-09-15 00:01:13+00:00,1,America/Los_Angeles
4,282b4e07171c48ac08162e0dc8749066,18fcf47148228c7b56c19726c854054b,9b8e9b8befe560293a6c5b38dc19ffbb,MT,None,http://www.mantecatransit.com,America/Los_Angeles,en,(209) 456-8000,None,None,aHR0cHM6Ly93d3cuY2kubWFudGVjYS5jYS51cy9Db21tdW...,2021-07-28,2021-07-28 13:56:16+00:00,1,America/Los_Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64250,4b3a0475f412b43b2193162af67b6d5e,53614dfeecf131052270c150f758385d,77b6f917c93cd0df914c4464babd89fb,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-21,2023-06-21 03:00:44.374286+00:00,51,America/New_York
64251,8036aa61601f9639e38e5badc9e695e5,0460c4af1cff0625899b79263efb4de9,7582dbee0bae7096dc852dbb1b08bfae,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-12,2023-06-12 03:00:19.345342+00:00,51,America/New_York
64252,d68573068cee2b62d39d4ec2984cfe4b,d4658c02796555dd0d7c2eb7e4591a72,c1e6cc82b6d90b887502c1968249bd09,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-14,2023-06-14 03:00:25.051132+00:00,51,America/New_York
64253,d6be150d01ed7bf9ad331b36bac61b30,4778fc73f3171660f3e238fee43d2cd3,78b7c565f05f6a62fd2b89b570ead696,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-17,2023-06-17 03:00:20.081767+00:00,51,America/New_York
64254,280057e38f45d53dbf28a93696cf4bee,baa4244fdd157a9af14e7d38469252eb,fe8f5d682c171239888eb51be6d14208,1238,MARC,http://www.amtrak.com,America/New_York,en,None,None,None,aHR0cHM6Ly9jb250ZW50LmFtdHJhay5jb20vY29udGVudC...,2023-06-13,2023-06-13 03:00:31.783490+00:00,51,America/New_York

In [59]:
df_dim_agency.groupby('agency_id').size().sort_index()

agency_id
0                                        156
01                                        18
05f0da90-7acf-491d-936c-5ee848a0e941      33
1                                       1224
100                                       21
                                        ...
samtrans-ca-us                            41
ucb                                        1
unitrans                                  77
wasco                                      2
west-hollywood                             4
Length: 332, dtype: int64

In [69]:
df_dim_agency.groupby('agency_id').last('agency_phone')

                                      _line_number
agency_id
0                                                1
01                                               1
05f0da90-7acf-491d-936c-5ee848a0e941             1
1                                                6
100                                              1
...                                            ...
samtrans-ca-us                                   1
ucb                                              1
unitrans                                         1
wasco                                            1
west-hollywood                                   1

[332 rows x 1 columns]

In [82]:
df_dim_agency.groupby('agency_id').mean()

/tmp/ipykernel_157/861259891.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_dim_agency.groupby('agency_id').mean()

                                      _line_number
agency_id
0                                         1.000000
01                                        1.000000
05f0da90-7acf-491d-936c-5ee848a0e941      1.000000
1                                         1.240196
100                                       1.000000
...                                            ...
samtrans-ca-us                            1.000000
ucb                                       1.000000
unitrans                                  1.000000
wasco                                     1.000000
west-hollywood                            1.000000

[332 rows x 1 columns]

In [ ]:
df_dim_agency = query_sql("""

select * 
from `mart_gtfs.dim_agency`

""", as_df = True)