In [1]:
import pandas as pd
import pandas_gbq

In [2]:
# get all activity for one route
# using Dumbarton Express as an example because it seems to have good data

dumbarton_route_db1_20230315_tu_raw = pd.read_gbq(
    """
    SELECT *
    FROM `cal-itp-data-infra.mart_ad_hoc.fct_stop_time_updates_20230315_to_20230321`
    WHERE base64_url = 'aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3RyaXB1cGRhdGVzP2FnZW5jeT1ERQ==' 
        AND service_date = '2023-03-15'
        AND trip_route_id = 'DB1'
    """, project_id = 'cal-itp-data-infra')

/opt/conda/lib/python3.9/site-packages/geopandas/_compat.py:123: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(
/opt/conda/lib/python3.9/site-packages/google/cloud/bigquery/table.py:43: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas  # type: ignore

In [ ]:
dumbarton_route_db1_20230315_tu_raw = pd.read_gbq(
    """
    SELECT *
    FROM `cal-itp-data-infra.mart_ad_hoc.fct_stop_time_updates_20230315_to_20230321`
    WHERE base64_url = 'aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3RyaXB1cGRhdGVzP2FnZW5jeT1ERQ==' 
        AND service_date = '2023-03-15'
        AND trip_route_id = 'DB1'
    """, project_id = 'cal-itp-data-infra')

In [ ]:
dumbarton_route_db1_20230315_tu_raw

In [3]:
db1_tu = dumbarton_route_db1_20230315_tu_raw.copy()

In [4]:
db1_tu.head()

,key,gtfs_dataset_key,dt,hour,base64_url,_extract_ts,_config_extract_ts,_gtfs_dataset_name,_header_message_age,_trip_update_message_age,...,arrival_delay,arrival_time,arrival_uncertainty,departure_delay,departure_time,departure_uncertainty,schedule_relationship,service_date,arrival_time_pacific,departure_time_pacific
0,8c170e832d6f62ed3b4f6982e9cf8df3,5c3e65766dda65958cf4da845286c0d5,2023-03-16,2023-03-16 00:00:00+00:00,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3RyaXB1cG...,2023-03-16 00:57:00+00:00,2023-03-15 19:04:01.925806+00:00,Bay Area 511 Dumbarton Express TripUpdates,19,4,...,3157,1678931180,<NA>,<NA>,<NA>,<NA>,None,2023-03-15,2023-03-15 18:46:20,NaT
1,fd44b37c3cacc92dd89e399977e626f3,5c3e65766dda65958cf4da845286c0d5,2023-03-16,2023-03-16 00:00:00+00:00,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3RyaXB1cG...,2023-03-16 00:57:00+00:00,2023-03-15 19:04:01.925806+00:00,Bay Area 511 Dumbarton Express TripUpdates,19,4,...,3176,1678931430,<NA>,<NA>,<NA>,<NA>,None,2023-03-15,2023-03-15 18:50:30,NaT
2,67190d2a9e8527d4ab8cb9cda9f95782,5c3e65766dda65958cf4da845286c0d5,2023-03-16,2023-03-16 00:00:00+00:00,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3RyaXB1cG...,2023-03-16 00:57:00+00:00,2023-03-15 19:04:01.925806+00:00,Bay Area 511 Dumbarton Express TripUpdates,19,4,...,262,1678933543,<NA>,<NA>,<NA>,<NA>,None,2023-03-15,2023-03-15 19:25:43,NaT
3,dfb4054c4db6d6a54d36263a8114b107,5c3e65766dda65958cf4da845286c0d5,2023-03-16,2023-03-16 00:00:00+00:00,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3RyaXB1cG...,2023-03-16 00:57:00+00:00,2023-03-15 19:04:01.925806+00:00,Bay Area 511 Dumbarton Express TripUpdates,19,4,...,1401,1678929648,<NA>,<NA>,<NA>,<NA>,None,2023-03-15,2023-03-15 18:20:48,NaT
4,056c2ce83d4fa8919134a510a23b2fd2,5c3e65766dda65958cf4da845286c0d5,2023-03-16,2023-03-16 00:00:00+00:00,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3RyaXB1cG...,2023-03-16 00:57:00+00:00,2023-03-15 19:04:01.925806+00:00,Bay Area 511 Dumbarton Express TripUpdates,19,4,...,-22,1678935309,<NA>,<NA>,<NA>,<NA>,None,2023-03-15,2023-03-15 19:55:09,NaT